---
name: Update Changelog
description: Update Changelog

inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Update Changelog
      shell: bash
      run: |
        npm install -g conventional-changelog-cli
        conventional-changelog -p angular -i CHANGELOG.md -s
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -m "docs: update changelog for dependabot PR #${{ github.event.pull_request.number }}" || echo "No changes"
        git fetch origin main
        git rebase origin/main
        git push --force-with-lease
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
