---
name: Update Changelog
description: Update Changelog

inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Update Changelog
      shell: bash
      run: |
        npm install -g conventional-changelog conventional-changelog-angular
        npx conventional-changelog -p angular -i CHANGELOG.md -s
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
