---
name: Setup python platform
description: Setup python platform

inputs:
  AWS_OIDC_ROLE_ARN:
    description: AWS oidc role arn
    required: true

runs:
  using: composite
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set shell options
        run: set -euxo pipefail

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.AWS_OIDC_ROLE_ARN }}
          role-session-name: aws-oidc-${{ github.repository.name }}-${{ github.run_id }}
          aws-region: us-east-1

      - run: pip install -r requirements.txt
