---
name: Docs apk update

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TZ: Asia/Singapore

jobs:
  run-push:
    continue-on-error: true
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        run: set -euxo pipefail

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          role-session-name: aws-oidc-${{ github.repository.name }}-${{ github.run_id }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to AWS ECR Public Registry
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2

      - run: pip install -r requirements.txt
        working-directory: docs

      - name: Run architecture-specific script
        working-directory: docs
        run: |
          if [ "${{ matrix.arch }}" == "amd64" ]; then
            python3 query-alpine-amd64-apk-info.py
          else
            python3 query-alpine-arm64-apk-info.py
          fi

      - name: 'commit update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Start."
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false
          git checkout main
          git pull origin main
          git add .
          git commit -m 'Automated documentation update [skip ci]' || echo "No changes to commit"

          if ! git push origin main; then
            echo "Push failed, trying git pull --rebase and push again..."
            git pull --rebase origin main
            git push origin main
          fi
